export const environment = {
  production: false,
  standalone: true,
  data: {
    timeline: {
      items: [
        {
          id: 1,
          title: "Sr Fullstack Software Developer",
          company: "TCS",
          location: "Guadalajara, Jalisco, México",
          startDate: "2021-10-25",
          endDate: null,
          description: ['Leveraged Angular, Java, Spring Boot, and PLSQL to develop and maintain robust web applications, resulting in a remarkable 50% increase in overall system performance.', 'Implemented comprehensive unit test cases, elevating the quality and efficiency of the systems code while achieving an impressive 80% increase in test coverage and significantly reducing post-deploy issues.', 'Utilized HTML and CSS to create compelling mockups, leading to the successful integration of two new modules into an enterprise system.'],
          visible: null,
        },
        {
          id: 2,
          title: "Sr Software Engineer",
          company: "Softtek",
          location: "Ciudad México, México",
          startDate: "2020-11-30",
          endDate: "2021-10-31",
          description: ["Developed and maintained robust web applications using Angular, Java, Quarkus, and MySQL, resulting in the creation of a reliable platform facilitating real-time communication among 1499 medical units in México.", "Created visually appealing and user-friendly mockups using HTML and CSS, contributing to the successful implementation of a new module with enhanced responsiveness and aesthetics.", "Designed and modified database tables and functions, resulting in the successful addition of two new functionalities to improve the overall system capabilities."],
          visible: null,
        },
        {
          id: 3,
          title: "Frontend Developer",
          company: "AITI",
          location: "Tlalnepantla, Estado de México, México",
          startDate: "2019-11-01",
          endDate: "2020-10-31",
          description: ["Designed from scratch, developed, deployed, and maintained a whole new E-commerce platform using Angular, Java, Spring Boot and MySQL resulting in a robust platform that handles thousands of transactions every day in México City.", "•	Redesigned web application with .NET, SQL, and Bootstrap resulting in a fully responsive user interface."],
          visible: null,
        },
        {
          id: 4,
          title: "Software Developer",
          company: "GO! Fitness",
          location: "Ciudad México, México",
          startDate: "2019-05-01",
          endDate: "2019-10-31",
          description: ["Designed from scratch, developed, deployed, and maintained a whole new E-commerce platform using Angular, PHP, Yii2 and MySQL resulting in a robust platform that handles thousands of transactions every day in México City."],
          visible: null,
        },
        {
          id: 5,
          title: "Technical Leader",
          company: "Indra",
          location: "Ciudad México, México",
          startDate: "2015-12-01",
          endDate: "2019-04-30",
          description: ["Led a team of 5 developers resulting in the design and implementation of three new web applications and the maintenance and operation of other 5 web applications already implemented.", "Developed and implemented MySQL functions and store procedures resulting in the generation of valuable reports for the stakeholders and the improvement of the system performance.", "Developed, operated, and deployed a web application that compares the fees of the hundreds of service providers all over the country, providing to the thousands of users."],
          visible: null,
        },
        {
          id: 6,
          title: "System Administrator",
          company: "Graphimedic",
          location: "Ciudad México, México",
          startDate: "2006-04-01",
          endDate: "2013-05-31",
          description: ["Developed and maintained a PHP application that resulted in a productivity increase of 60%.", "Developed hundreds of HTML pages with CSS resulting in the digital publication of clinical and scientific articles."],
          visible: null,
        },
      ],
    }
  },
};

export const environment = {
  production: false,
  standalone: true,
  data: {
    timeline: {
      items: [
        {
          id: 1,
          title: "Sr Fullstack Software Developer",
          company: "TCS",
          location: "Guadalajara, Jalisco, México",
          startDate: "2021-10-25",
          endDate: null,
          detail: "Work in a multicultural environment developing and mantaining a ERP for a Finacial Market Enterprise.in the USA.",
          description: ['Leveraged Angular, Java, Spring Boot, and PLSQL to develop and maintain robust web applications, resulting in a remarkable 50% increase in overall system performance.', 'Implemented comprehensive unit test cases, elevating the quality and efficiency of the systems code while achieving an impressive 80% increase in test coverage and significantly reducing post-deploy issues.', 'Utilized HTML and CSS to create compelling mockups, leading to the successful integration of two new modules into an enterprise system.'],
          visible: null,
        },
        {
          id: 2,
          title: "Sr Software Engineer",
          company: "Softtek",
          location: "Ciudad México, México",
          startDate: "2020-11-30",
          endDate: "2021-10-31",
          detail: "Created a real time communication platform for the mexican public healthcare institution, the platform is currently used by 40,000 medical centers and hospitals all over the country.",
          description: ["Developed and maintained robust web applications using Angular, Java, Quarkus, and MySQL, resulting in the creation of a reliable platform facilitating real-time communication among 1499 medical units in México.", "Created visually appealing and user-friendly mockups using HTML and CSS, contributing to the successful implementation of a new module with enhanced responsiveness and aesthetics.", "Designed and modified database tables and functions, resulting in the successful addition of two new functionalities to improve the overall system capabilities."],
          visible: null,
        },
        {
          id: 3,
          title: "Frontend Developer",
          company: "AITI",
          location: "Tlalnepantla, Estado de México, México",
          startDate: "2019-11-01",
          endDate: "2020-10-31",
          detail: "Created a new E-commerce platform for a mexican retail company, using cutting edge technologies like Angular, Java, Spring Boot and MySQL.",
          description: ["Designed from scratch, developed, deployed, and maintained a whole new E-commerce platform using Angular, Java, Spring Boot and MySQL resulting in a robust platform that handles thousands of transactions every day in México City.", "•	Redesigned web application with .NET, SQL, and Bootstrap resulting in a fully responsive user interface."],
          visible: null,
        },
        {
          id: 4,
          title: "Software Developer",
          company: "GO! Fitness",
          location: "Ciudad México, México",
          startDate: "2019-05-01",
          endDate: "2019-10-31",
          detail: "Created a new E-commerce platform for a mexican retail company.",
          description: ["Designed from scratch, developed, deployed, and maintained a whole new E-commerce platform using Angular, PHP, Yii2 and MySQL resulting in a robust platform that handles thousands of transactions every day in México City."],
          visible: null,
        },
        {
          id: 5,
          title: "Technical Leader",
          company: "Indra",
          location: "Ciudad México, México",
          startDate: "2015-12-01",
          endDate: "2019-04-30",
          detail: "Led a team of 5 developers resulting in the design and implementation of three new web applications and the maintenance and operation of other 5 web applications already implemented.",
          description: ["Led a team of 5 developers resulting in the design and implementation of three new web applications and the maintenance and operation of other 5 web applications already implemented.", "Developed and implemented MySQL functions and store procedures resulting in the generation of valuable reports for the stakeholders and the improvement of the system performance.", "Developed, operated, and deployed a web application that compares the fees of the hundreds of service providers all over the country, providing to the thousands of users."],
          visible: null,
        },
        {
          id: 6,
          title: "System Administrator",
          company: "Graphimedic",
          location: "Ciudad México, México",
          startDate: "2006-04-01",
          endDate: "2013-05-31",
          detail: "Developed and maintained a PHP application that resulted in a productivity increase of 60%.",
          description: ["Developed and maintained a PHP application that resulted in a productivity increase of 60%.", "Developed hundreds of HTML pages with CSS resulting in the digital publication of clinical and scientific articles."],
          visible: null,
        },
      ],
    }
  },
};
